name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        image:
          - ack
          - all-jdks
          - bazel
          - careercup
          - groovy-graphviz-jenkins-slave
          - logstash
          - oracle-xe-11g
          - pcat
          - quincykit
          - rubygems-servlets
          - tfjava
          - tika

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        working-directory: ${{matrix.image}}
        run: docker build . --file Dockerfile --tag rahulsom/${{matrix.image}}:$(date +%s)
