name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        image: [ "ack" ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build ACK
      working-directory: ${{matrix.image}}
      run: docker build . --file Dockerfile --tag rahulsom/${{matrix.image}}:$(date +%s)
